export interface CareerRole {
  id: string;
  title: string;
  category: "popular" | "emerging" | "hybrid";
  field: string;
  salaryRange: string;
  education: string;
  growthRate: string;
  skills: string[];
  dayToDay: string;
  relatedRoles: string[];
  description: string;
}

export const careerRoles: CareerRole[] = [
  // Popular Roles
  { id: "p1", title: "Software Engineer", category: "popular", field: "Software & Tech", salaryRange: "$120K–$180K", education: "BS in Computer Science or equivalent", growthRate: "25%", skills: ["JavaScript/TypeScript", "System Design", "Data Structures", "Git", "Cloud (AWS/GCP)"], dayToDay: "Design, build, and ship features in a codebase. Collaborate with product and design teams. Review code, debug issues, and participate in sprint planning.", relatedRoles: ["Full-Stack Developer", "Backend Engineer", "DevOps Engineer"], description: "Build software products used by millions. High demand across every industry." },
  { id: "p2", title: "Data Scientist", category: "popular", field: "Software & Tech", salaryRange: "$110K–$160K", education: "BS/MS in Statistics, CS, or Math", growthRate: "36%", skills: ["Python", "SQL", "Machine Learning", "Statistics", "Data Visualization"], dayToDay: "Analyze large datasets to find patterns. Build predictive models. Present insights to stakeholders and inform business decisions.", relatedRoles: ["Data Analyst", "ML Engineer", "Business Intelligence Analyst"], description: "Turn data into actionable insights. One of the fastest-growing roles in tech." },
  { id: "p3", title: "Physician", category: "popular", field: "Healthcare & Medicine", salaryRange: "$200K–$350K", education: "MD + Residency (11+ years)", growthRate: "3%", skills: ["Clinical Diagnosis", "Patient Care", "Medical Research", "Communication", "Anatomy"], dayToDay: "Diagnose and treat patients. Order tests, prescribe medications. Manage patient relationships and stay current with medical research.", relatedRoles: ["Surgeon", "Psychiatrist", "Physician Assistant"], description: "Highest-paid profession with deep impact on human life. Long training path." },
  { id: "p4", title: "Financial Analyst", category: "popular", field: "Business & Finance", salaryRange: "$85K–$130K", education: "BS in Finance or Economics", growthRate: "9%", skills: ["Financial Modeling", "Excel", "Data Analysis", "Valuation", "Presentation"], dayToDay: "Build financial models, analyze company performance, prepare reports for leadership, and support investment decisions.", relatedRoles: ["Investment Banker", "Portfolio Manager", "Risk Analyst"], description: "Gateway role to Wall Street and corporate finance. Strong analytical foundation." },
  { id: "p5", title: "UX Designer", category: "popular", field: "Creative & Design", salaryRange: "$80K–$130K", education: "BS in Design, HCI, or self-taught", growthRate: "16%", skills: ["Figma", "User Research", "Prototyping", "Interaction Design", "Accessibility"], dayToDay: "Conduct user research, create wireframes and prototypes, run usability tests, and iterate on designs with engineering teams.", relatedRoles: ["UI Designer", "Product Designer", "Design Researcher"], description: "Shape how millions of people interact with digital products." },
  { id: "p6", title: "Mechanical Engineer", category: "popular", field: "Engineering", salaryRange: "$90K–$140K", education: "BS in Mechanical Engineering", growthRate: "7%", skills: ["CAD/SolidWorks", "Thermodynamics", "Materials Science", "FEA", "Manufacturing"], dayToDay: "Design mechanical components, run simulations, prototype and test parts, collaborate with manufacturing teams.", relatedRoles: ["Aerospace Engineer", "Robotics Engineer", "Manufacturing Engineer"], description: "Design physical systems from cars to spacecraft. Foundational engineering discipline." },

  // Emerging & Niche Roles
  { id: "e1", title: "MLOps Engineer", category: "emerging", field: "Software & Tech", salaryRange: "$140K–$200K", education: "BS/MS in CS or Data Science", growthRate: "45%+", skills: ["Python", "Docker/K8s", "ML Pipelines", "Cloud Infrastructure", "CI/CD"], dayToDay: "Build and maintain ML model deployment pipelines. Monitor model performance in production. Bridge the gap between data science and engineering.", relatedRoles: ["ML Engineer", "Platform Engineer", "Data Engineer"], description: "Rapidly growing role as companies operationalize AI. Combines DevOps with ML." },
  { id: "e2", title: "Developer Relations Engineer", category: "emerging", field: "Software & Tech", salaryRange: "$120K–$170K", education: "BS in CS + communication skills", growthRate: "30%+", skills: ["Technical Writing", "Public Speaking", "SDK Development", "Community Building", "Content Creation"], dayToDay: "Create tutorials, speak at conferences, engage developer communities, provide feedback to product teams, and build sample apps.", relatedRoles: ["Technical Writer", "Solutions Engineer", "Developer Advocate"], description: "Be the bridge between a company and its developer community. Part engineer, part communicator." },
  { id: "e3", title: "Climate Tech Analyst", category: "emerging", field: "Engineering", salaryRange: "$80K–$130K", education: "BS in Environmental Science/Engineering", growthRate: "25%+", skills: ["Carbon Accounting", "LCA Analysis", "Policy Analysis", "Data Modeling", "Sustainability Reporting"], dayToDay: "Analyze carbon footprints, evaluate clean energy investments, track ESG metrics, and advise companies on sustainability strategy.", relatedRoles: ["Sustainability Consultant", "Clean Energy Engineer", "ESG Analyst"], description: "Fast-growing field as companies and governments invest in climate solutions." },
  { id: "e4", title: "Health Informatics Specialist", category: "emerging", field: "Healthcare & Medicine", salaryRange: "$85K–$130K", education: "BS/MS in Health Informatics", growthRate: "17%", skills: ["EHR Systems", "Data Analytics", "HIPAA Compliance", "SQL", "Clinical Workflows"], dayToDay: "Optimize healthcare data systems, implement EHR solutions, analyze patient data for quality improvement, train clinical staff.", relatedRoles: ["Clinical Data Analyst", "Health IT Manager", "Biomedical Informatics Researcher"], description: "Where healthcare meets technology. Growing rapidly with digital health adoption." },
  { id: "e5", title: "Product-Led Growth Manager", category: "emerging", field: "Business & Finance", salaryRange: "$110K–$160K", education: "BS in Business/Marketing + analytics", growthRate: "35%+", skills: ["Product Analytics", "A/B Testing", "Growth Modeling", "SQL", "User Psychology"], dayToDay: "Design and run growth experiments, analyze user funnels, optimize onboarding flows, collaborate with product and engineering teams.", relatedRoles: ["Growth Engineer", "Product Manager", "Marketing Analyst"], description: "Blend of product, marketing, and data. Key role at SaaS and startup companies." },

  // Hybrid & Non-Traditional Paths
  { id: "h1", title: "Technical Product Manager", category: "hybrid", field: "Software & Tech", salaryRange: "$130K–$190K", education: "BS in CS/Engineering + MBA optional", growthRate: "20%", skills: ["Product Strategy", "Technical Architecture", "Stakeholder Management", "Data Analysis", "Agile/Scrum"], dayToDay: "Define product roadmap, prioritize features with engineering, analyze user data, run sprint ceremonies, present to leadership.", relatedRoles: ["Product Manager", "Engineering Manager", "Solutions Architect"], description: "Lead products that require deep technical understanding. Bridge business and engineering." },
  { id: "h2", title: "Computational Biologist", category: "hybrid", field: "Science & Research", salaryRange: "$95K–$150K", education: "PhD in Biology/Bioinformatics", growthRate: "15%", skills: ["Python/R", "Genomics", "Statistical Modeling", "Machine Learning", "Molecular Biology"], dayToDay: "Analyze genomic data, build computational models of biological systems, collaborate with lab scientists, publish research findings.", relatedRoles: ["Bioinformatician", "Research Scientist", "Drug Discovery Scientist"], description: "Apply CS and math to solve biological problems. Critical for drug discovery and genomics." },
  { id: "h3", title: "Creative Technologist", category: "hybrid", field: "Creative & Design", salaryRange: "$90K–$150K", education: "BS in Design/CS or self-taught", growthRate: "18%", skills: ["Creative Coding", "WebGL/Three.js", "Generative Art", "Interaction Design", "Prototyping"], dayToDay: "Build immersive digital experiences, create interactive installations, prototype novel interfaces, push boundaries of design and tech.", relatedRoles: ["Frontend Engineer", "Motion Designer", "XR Developer"], description: "Blend art and code. Build experiences that wow people — from interactive installations to generative art." },
  { id: "h4", title: "Legal Engineer", category: "hybrid", field: "Law & Policy", salaryRange: "$100K–$160K", education: "JD + technical skills or BS CS + legal knowledge", growthRate: "22%", skills: ["Contract Automation", "Legal Tech Platforms", "Process Design", "Compliance Frameworks", "Data Privacy"], dayToDay: "Build and implement legal technology solutions, automate contract workflows, design compliance systems, bridge legal and engineering teams.", relatedRoles: ["Legal Operations Manager", "Privacy Engineer", "Compliance Analyst"], description: "Emerging role at the intersection of law and technology. Automate legal processes at scale." },

  // ── Additional Popular Roles ──
  { id: "p7", title: "Registered Nurse", category: "popular", field: "Healthcare & Medicine", salaryRange: "$60K–$110K", education: "BSN or ADN + RN License", growthRate: "6%", skills: ["Patient Assessment", "IV Therapy", "EMR Documentation", "Critical Thinking", "Pharmacology"], dayToDay: "Administer medications, monitor vitals, coordinate with physicians, educate patients and families, manage care plans.", relatedRoles: ["Nurse Practitioner", "Clinical Nurse Specialist", "Nurse Anesthetist"], description: "Backbone of healthcare. Diverse specializations from ER to pediatrics to oncology." },
  { id: "p8", title: "Product Manager", category: "popular", field: "Software & Tech", salaryRange: "$110K–$170K", education: "BS in any field + product experience", growthRate: "22%", skills: ["Product Strategy", "User Research", "Data Analysis", "Roadmapping", "Cross-functional Leadership"], dayToDay: "Define what to build and why. Prioritize features, write PRDs, analyze metrics, coordinate engineering/design/marketing.", relatedRoles: ["Technical Product Manager", "Growth PM", "Product Owner"], description: "Own the 'what' and 'why' of products. High-impact role requiring business + technical fluency." },
  { id: "p9", title: "Civil Engineer", category: "popular", field: "Engineering", salaryRange: "$75K–$120K", education: "BS in Civil Engineering + PE License", growthRate: "8%", skills: ["AutoCAD", "Structural Analysis", "Project Management", "Environmental Compliance", "Geotechnical"], dayToDay: "Design infrastructure (bridges, roads, buildings), manage construction projects, ensure code compliance, conduct site surveys.", relatedRoles: ["Structural Engineer", "Transportation Engineer", "Environmental Engineer"], description: "Build the infrastructure society depends on. Stable demand with infrastructure spending." },
  { id: "p10", title: "Marketing Manager", category: "popular", field: "Marketing & Communications", salaryRange: "$80K–$140K", education: "BS in Marketing or Business", growthRate: "10%", skills: ["Brand Strategy", "Digital Marketing", "Analytics", "Content Strategy", "Campaign Management"], dayToDay: "Plan and execute marketing campaigns, analyze performance metrics, manage budgets, coordinate with creative and sales teams.", relatedRoles: ["Brand Manager", "Digital Marketing Director", "Content Strategist"], description: "Drive brand growth and customer acquisition. Blend of creativity and data-driven decision-making." },
  { id: "p11", title: "Accountant / CPA", category: "popular", field: "Business & Finance", salaryRange: "$65K–$110K", education: "BS in Accounting + CPA License", growthRate: "6%", skills: ["GAAP", "Tax Planning", "Auditing", "Financial Reporting", "Excel/QuickBooks"], dayToDay: "Prepare financial statements, manage tax filings, conduct audits, advise on financial compliance and planning.", relatedRoles: ["Tax Advisor", "Forensic Accountant", "Controller"], description: "Essential to every organization. CPA license opens doors to high-earning specializations." },
  { id: "p12", title: "Teacher / Educator", category: "popular", field: "Education & Teaching", salaryRange: "$45K–$80K", education: "BS in Education + Teaching License", growthRate: "5%", skills: ["Curriculum Design", "Classroom Management", "Differentiated Instruction", "Assessment", "Communication"], dayToDay: "Plan lessons, deliver instruction, assess student progress, communicate with parents, mentor students.", relatedRoles: ["School Counselor", "Curriculum Developer", "Education Administrator"], description: "Shape the next generation. Deep purpose-driven work with growing demand for STEM educators." },
  { id: "p13", title: "Lawyer / Attorney", category: "popular", field: "Law & Policy", salaryRange: "$90K–$200K+", education: "JD (3 years) + Bar Exam", growthRate: "10%", skills: ["Legal Research", "Argumentation", "Contract Drafting", "Negotiation", "Client Management"], dayToDay: "Research case law, draft legal documents, represent clients in court or negotiations, advise on legal strategy.", relatedRoles: ["Corporate Counsel", "Public Defender", "Legal Consultant"], description: "Advocate for clients in complex legal matters. Diverse specializations from corporate to criminal to IP law." },
  { id: "p14", title: "Cybersecurity Analyst", category: "popular", field: "Software & Tech", salaryRange: "$90K–$150K", education: "BS in CS/Cybersecurity + certifications", growthRate: "32%", skills: ["Network Security", "Penetration Testing", "SIEM Tools", "Incident Response", "Compliance (SOC2/ISO)"], dayToDay: "Monitor systems for threats, conduct vulnerability assessments, respond to incidents, implement security policies.", relatedRoles: ["Security Engineer", "Penetration Tester", "CISO"], description: "Protect organizations from cyber threats. Massive talent shortage means high demand and fast career growth." },

  // ── Additional Emerging Roles ──
  { id: "e6", title: "AI Prompt Engineer", category: "emerging", field: "Software & Tech", salaryRange: "$100K–$160K", education: "BS in CS/Linguistics or self-taught", growthRate: "50%+", skills: ["Prompt Design", "LLM APIs", "Python", "NLP Concepts", "Evaluation Metrics"], dayToDay: "Design and optimize prompts for AI models, evaluate output quality, build prompt pipelines, document best practices.", relatedRoles: ["AI Engineer", "NLP Researcher", "ML Engineer"], description: "Brand-new role born from the AI revolution. Craft the instructions that make AI systems useful." },
  { id: "e7", title: "Robotics Process Automation Developer", category: "emerging", field: "Software & Tech", salaryRange: "$90K–$140K", education: "BS in CS or IT + RPA certification", growthRate: "30%", skills: ["UiPath/Automation Anywhere", "Process Mapping", "Python/VBA", "Business Analysis", "Testing"], dayToDay: "Automate repetitive business processes using RPA tools, analyze workflows, build and maintain bots, train business users.", relatedRoles: ["Automation Engineer", "Business Process Analyst", "Solutions Developer"], description: "Automate mundane work so humans focus on higher-value tasks. Huge demand across finance, healthcare, and ops." },
  { id: "e8", title: "Behavioral Economist", category: "emerging", field: "Science & Research", salaryRange: "$85K–$140K", education: "MS/PhD in Economics or Psychology", growthRate: "12%", skills: ["Experimental Design", "Statistics", "Behavioral Science", "Policy Analysis", "Data Analysis"], dayToDay: "Design experiments to understand decision-making, analyze behavioral data, advise organizations on nudge strategies.", relatedRoles: ["Research Scientist", "UX Researcher", "Policy Analyst"], description: "Apply psychology to economics. Help companies and governments design better choices for people." },
  { id: "e9", title: "Spatial Computing Developer", category: "emerging", field: "Software & Tech", salaryRange: "$120K–$180K", education: "BS in CS + XR development experience", growthRate: "40%+", skills: ["Unity/Unreal", "3D Math", "ARKit/ARCore", "Spatial UI Design", "C#/C++"], dayToDay: "Build AR/VR/MR applications, design spatial interfaces, optimize 3D rendering, prototype immersive experiences.", relatedRoles: ["XR Developer", "3D Engineer", "Game Developer"], description: "Build the next computing platform. Apple Vision Pro and Meta Quest are creating massive demand for spatial developers." },
  { id: "e10", title: "Sustainability Manager", category: "emerging", field: "Business & Finance", salaryRange: "$80K–$130K", education: "BS in Environmental Science/Business", growthRate: "20%", skills: ["ESG Reporting", "Carbon Strategy", "Supply Chain Analysis", "Stakeholder Engagement", "Policy Compliance"], dayToDay: "Develop sustainability strategy, track ESG metrics, manage supplier audits, report to board on environmental impact.", relatedRoles: ["ESG Analyst", "Corporate Social Responsibility Manager", "Climate Consultant"], description: "Companies need sustainability leaders as regulations and consumer expectations evolve." },

  // ── Additional Hybrid Roles ──
  { id: "h5", title: "Science Communicator", category: "hybrid", field: "Science & Research", salaryRange: "$55K–$100K", education: "BS in Science + communication skills", growthRate: "14%", skills: ["Science Writing", "Video Production", "Public Speaking", "Social Media", "Research Translation"], dayToDay: "Translate complex research into accessible content, produce educational media, engage public audiences, fact-check claims.", relatedRoles: ["Science Journalist", "Documentary Producer", "Museum Educator"], description: "Make science understandable and exciting. From YouTube channels to museum exhibits to policy briefs." },
  { id: "h6", title: "Healthcare Data Analyst", category: "hybrid", field: "Healthcare & Medicine", salaryRange: "$75K–$120K", education: "BS in Health Informatics or Data Science", growthRate: "18%", skills: ["SQL", "Python/R", "EHR Data", "HIPAA", "Statistical Analysis"], dayToDay: "Analyze clinical and operational data, build dashboards, identify trends in patient outcomes, support evidence-based decisions.", relatedRoles: ["Clinical Analyst", "Population Health Analyst", "Health IT Specialist"], description: "Bridge healthcare domain expertise with data skills. Growing rapidly with digital health transformation." },
  { id: "h7", title: "Design Strategist", category: "hybrid", field: "Creative & Design", salaryRange: "$100K–$155K", education: "BS/MFA in Design + business acumen", growthRate: "16%", skills: ["Design Thinking", "Business Strategy", "User Research", "Workshop Facilitation", "Systems Thinking"], dayToDay: "Lead design-driven innovation, facilitate strategy workshops, connect design decisions to business outcomes, mentor teams.", relatedRoles: ["Service Designer", "Innovation Consultant", "UX Director"], description: "Use design methodology to solve business problems. Strategic role bridging creativity and business." },
  { id: "h8", title: "Bioethicist", category: "hybrid", field: "Law & Policy", salaryRange: "$70K–$120K", education: "PhD in Bioethics/Philosophy + science background", growthRate: "10%", skills: ["Ethical Analysis", "Policy Writing", "Research Ethics", "Public Engagement", "Clinical Ethics Consultation"], dayToDay: "Advise on ethical dilemmas in healthcare, research, and AI. Review IRB proposals, develop ethics guidelines, educate professionals.", relatedRoles: ["Medical Ethicist", "AI Ethics Researcher", "Policy Advisor"], description: "Navigate the moral dimensions of science and technology. Critical as AI and genomics raise new ethical questions." },
  { id: "h9", title: "Urban Planner", category: "hybrid", field: "Engineering", salaryRange: "$60K–$100K", education: "MUP or BS in Urban Planning/Geography", growthRate: "11%", skills: ["GIS", "Zoning Regulations", "Community Engagement", "Environmental Planning", "Transportation Analysis"], dayToDay: "Design land use plans, conduct community outreach, analyze demographics, review development proposals, advise city councils.", relatedRoles: ["Transportation Planner", "Environmental Planner", "Real Estate Developer"], description: "Shape how cities and communities grow. Blend of policy, design, and engineering for public good." },
];

export function getCareersForProfile(interests: string[]): { popular: CareerRole[]; emerging: CareerRole[]; hybrid: CareerRole[] } {
  const relevant = careerRoles.filter(r => interests.includes(r.field) || interests.length === 0);
  const all = relevant.length > 0 ? relevant : careerRoles;
  return {
    popular: all.filter(r => r.category === "popular"),
    emerging: all.filter(r => r.category === "emerging"),
    hybrid: all.filter(r => r.category === "hybrid"),
  };
}
