export interface CareerRole {
  id: string;
  title: string;
  category: "popular" | "emerging" | "hybrid";
  field: string;
  salaryRange: string;
  education: string;
  growthRate: string;
  skills: string[];
  dayToDay: string;
  relatedRoles: string[];
  description: string;
}

export const careerRoles: CareerRole[] = [
  // Popular Roles
  { id: "p1", title: "Software Engineer", category: "popular", field: "Software & Tech", salaryRange: "$120K–$180K", education: "BS in Computer Science or equivalent", growthRate: "25%", skills: ["JavaScript/TypeScript", "System Design", "Data Structures", "Git", "Cloud (AWS/GCP)"], dayToDay: "Design, build, and ship features in a codebase. Collaborate with product and design teams. Review code, debug issues, and participate in sprint planning.", relatedRoles: ["Full-Stack Developer", "Backend Engineer", "DevOps Engineer"], description: "Build software products used by millions. High demand across every industry." },
  { id: "p2", title: "Data Scientist", category: "popular", field: "Software & Tech", salaryRange: "$110K–$160K", education: "BS/MS in Statistics, CS, or Math", growthRate: "36%", skills: ["Python", "SQL", "Machine Learning", "Statistics", "Data Visualization"], dayToDay: "Analyze large datasets to find patterns. Build predictive models. Present insights to stakeholders and inform business decisions.", relatedRoles: ["Data Analyst", "ML Engineer", "Business Intelligence Analyst"], description: "Turn data into actionable insights. One of the fastest-growing roles in tech." },
  { id: "p3", title: "Physician", category: "popular", field: "Healthcare & Medicine", salaryRange: "$200K–$350K", education: "MD + Residency (11+ years)", growthRate: "3%", skills: ["Clinical Diagnosis", "Patient Care", "Medical Research", "Communication", "Anatomy"], dayToDay: "Diagnose and treat patients. Order tests, prescribe medications. Manage patient relationships and stay current with medical research.", relatedRoles: ["Surgeon", "Psychiatrist", "Physician Assistant"], description: "Highest-paid profession with deep impact on human life. Long training path." },
  { id: "p4", title: "Financial Analyst", category: "popular", field: "Business & Finance", salaryRange: "$85K–$130K", education: "BS in Finance or Economics", growthRate: "9%", skills: ["Financial Modeling", "Excel", "Data Analysis", "Valuation", "Presentation"], dayToDay: "Build financial models, analyze company performance, prepare reports for leadership, and support investment decisions.", relatedRoles: ["Investment Banker", "Portfolio Manager", "Risk Analyst"], description: "Gateway role to Wall Street and corporate finance. Strong analytical foundation." },
  { id: "p5", title: "UX Designer", category: "popular", field: "Creative & Design", salaryRange: "$80K–$130K", education: "BS in Design, HCI, or self-taught", growthRate: "16%", skills: ["Figma", "User Research", "Prototyping", "Interaction Design", "Accessibility"], dayToDay: "Conduct user research, create wireframes and prototypes, run usability tests, and iterate on designs with engineering teams.", relatedRoles: ["UI Designer", "Product Designer", "Design Researcher"], description: "Shape how millions of people interact with digital products." },
  { id: "p6", title: "Mechanical Engineer", category: "popular", field: "Engineering", salaryRange: "$90K–$140K", education: "BS in Mechanical Engineering", growthRate: "7%", skills: ["CAD/SolidWorks", "Thermodynamics", "Materials Science", "FEA", "Manufacturing"], dayToDay: "Design mechanical components, run simulations, prototype and test parts, collaborate with manufacturing teams.", relatedRoles: ["Aerospace Engineer", "Robotics Engineer", "Manufacturing Engineer"], description: "Design physical systems from cars to spacecraft. Foundational engineering discipline." },

  // Emerging & Niche Roles
  { id: "e1", title: "MLOps Engineer", category: "emerging", field: "Software & Tech", salaryRange: "$140K–$200K", education: "BS/MS in CS or Data Science", growthRate: "45%+", skills: ["Python", "Docker/K8s", "ML Pipelines", "Cloud Infrastructure", "CI/CD"], dayToDay: "Build and maintain ML model deployment pipelines. Monitor model performance in production. Bridge the gap between data science and engineering.", relatedRoles: ["ML Engineer", "Platform Engineer", "Data Engineer"], description: "Rapidly growing role as companies operationalize AI. Combines DevOps with ML." },
  { id: "e2", title: "Developer Relations Engineer", category: "emerging", field: "Software & Tech", salaryRange: "$120K–$170K", education: "BS in CS + communication skills", growthRate: "30%+", skills: ["Technical Writing", "Public Speaking", "SDK Development", "Community Building", "Content Creation"], dayToDay: "Create tutorials, speak at conferences, engage developer communities, provide feedback to product teams, and build sample apps.", relatedRoles: ["Technical Writer", "Solutions Engineer", "Developer Advocate"], description: "Be the bridge between a company and its developer community. Part engineer, part communicator." },
  { id: "e3", title: "Climate Tech Analyst", category: "emerging", field: "Engineering", salaryRange: "$80K–$130K", education: "BS in Environmental Science/Engineering", growthRate: "25%+", skills: ["Carbon Accounting", "LCA Analysis", "Policy Analysis", "Data Modeling", "Sustainability Reporting"], dayToDay: "Analyze carbon footprints, evaluate clean energy investments, track ESG metrics, and advise companies on sustainability strategy.", relatedRoles: ["Sustainability Consultant", "Clean Energy Engineer", "ESG Analyst"], description: "Fast-growing field as companies and governments invest in climate solutions." },
  { id: "e4", title: "Health Informatics Specialist", category: "emerging", field: "Healthcare & Medicine", salaryRange: "$85K–$130K", education: "BS/MS in Health Informatics", growthRate: "17%", skills: ["EHR Systems", "Data Analytics", "HIPAA Compliance", "SQL", "Clinical Workflows"], dayToDay: "Optimize healthcare data systems, implement EHR solutions, analyze patient data for quality improvement, train clinical staff.", relatedRoles: ["Clinical Data Analyst", "Health IT Manager", "Biomedical Informatics Researcher"], description: "Where healthcare meets technology. Growing rapidly with digital health adoption." },
  { id: "e5", title: "Product-Led Growth Manager", category: "emerging", field: "Business & Finance", salaryRange: "$110K–$160K", education: "BS in Business/Marketing + analytics", growthRate: "35%+", skills: ["Product Analytics", "A/B Testing", "Growth Modeling", "SQL", "User Psychology"], dayToDay: "Design and run growth experiments, analyze user funnels, optimize onboarding flows, collaborate with product and engineering teams.", relatedRoles: ["Growth Engineer", "Product Manager", "Marketing Analyst"], description: "Blend of product, marketing, and data. Key role at SaaS and startup companies." },

  // Hybrid & Non-Traditional Paths
  { id: "h1", title: "Technical Product Manager", category: "hybrid", field: "Software & Tech", salaryRange: "$130K–$190K", education: "BS in CS/Engineering + MBA optional", growthRate: "20%", skills: ["Product Strategy", "Technical Architecture", "Stakeholder Management", "Data Analysis", "Agile/Scrum"], dayToDay: "Define product roadmap, prioritize features with engineering, analyze user data, run sprint ceremonies, present to leadership.", relatedRoles: ["Product Manager", "Engineering Manager", "Solutions Architect"], description: "Lead products that require deep technical understanding. Bridge business and engineering." },
  { id: "h2", title: "Computational Biologist", category: "hybrid", field: "Science & Research", salaryRange: "$95K–$150K", education: "PhD in Biology/Bioinformatics", growthRate: "15%", skills: ["Python/R", "Genomics", "Statistical Modeling", "Machine Learning", "Molecular Biology"], dayToDay: "Analyze genomic data, build computational models of biological systems, collaborate with lab scientists, publish research findings.", relatedRoles: ["Bioinformatician", "Research Scientist", "Drug Discovery Scientist"], description: "Apply CS and math to solve biological problems. Critical for drug discovery and genomics." },
  { id: "h3", title: "Creative Technologist", category: "hybrid", field: "Creative & Design", salaryRange: "$90K–$150K", education: "BS in Design/CS or self-taught", growthRate: "18%", skills: ["Creative Coding", "WebGL/Three.js", "Generative Art", "Interaction Design", "Prototyping"], dayToDay: "Build immersive digital experiences, create interactive installations, prototype novel interfaces, push boundaries of design and tech.", relatedRoles: ["Frontend Engineer", "Motion Designer", "XR Developer"], description: "Blend art and code. Build experiences that wow people — from interactive installations to generative art." },
  { id: "h4", title: "Legal Engineer", category: "hybrid", field: "Law & Policy", salaryRange: "$100K–$160K", education: "JD + technical skills or BS CS + legal knowledge", growthRate: "22%", skills: ["Contract Automation", "Legal Tech Platforms", "Process Design", "Compliance Frameworks", "Data Privacy"], dayToDay: "Build and implement legal technology solutions, automate contract workflows, design compliance systems, bridge legal and engineering teams.", relatedRoles: ["Legal Operations Manager", "Privacy Engineer", "Compliance Analyst"], description: "Emerging role at the intersection of law and technology. Automate legal processes at scale." },
];

export function getCareersForProfile(interests: string[]): { popular: CareerRole[]; emerging: CareerRole[]; hybrid: CareerRole[] } {
  const relevant = careerRoles.filter(r => interests.includes(r.field) || interests.length === 0);
  const all = relevant.length > 0 ? relevant : careerRoles;
  return {
    popular: all.filter(r => r.category === "popular"),
    emerging: all.filter(r => r.category === "emerging"),
    hybrid: all.filter(r => r.category === "hybrid"),
  };
}
